import fs from "fs";
import path from "path";
import chalk from "chalk";
import type { GeneratorOptions } from "./github-actions";
import { loadCICDTemplate, logTemplateSource } from "./template-loader";

export async function generateAzureDevOps(
	outputDir: string,
	options: GeneratorOptions,
): Promise<void> {
	// Try remote template, fall back to embedded
	const result = await loadCICDTemplate(
		"azure",
		options.strategy,
		options,
		generateAzureContentEmbedded,
	);

	logTemplateSource("Azure DevOps", result.source);

	const filePath = path.join(outputDir, "azure-pipelines.yml");
	fs.writeFileSync(filePath, result.content, "utf-8");
	console.log(chalk.green(`  ✓ Created azure-pipelines.yml`));
}

/**
 * Embedded template generator (fallback when remote templates unavailable)
 */
function generateAzureContentEmbedded(options: GeneratorOptions): string {
	const {
		projectName,
		nodeVersion,
		packageManager,
		strategy,
		includeSecurity,
		includeE2E,
		includeCoverage,
		deployTarget,
		branch,
		port,
	} = options;

	const installCmd =
		packageManager === "pnpm"
			? "pnpm install"
			: packageManager === "yarn"
				? "yarn install"
				: "npm ci";
	const testCmd =
		packageManager === "pnpm"
			? "pnpm test"
			: packageManager === "yarn"
				? "yarn test"
				: "npm test";
	const buildCmd =
		packageManager === "pnpm"
			? "pnpm build"
			: packageManager === "yarn"
				? "yarn build"
				: "npm run build";
	const lintCmd =
		packageManager === "pnpm"
			? "pnpm lint"
			: packageManager === "yarn"
				? "yarn lint"
				: "npm run lint";

	let content = `# Azure DevOps Pipeline
# Generated by ExpressoTS CLI
# Strategy: ${strategy}

trigger:
  branches:
    include:
      - ${branch}
  paths:
    exclude:
      - '*.md'
      - 'docs/*'

pr:
  branches:
    include:
      - ${branch}

variables:
  nodeVersion: '${nodeVersion}'
  dockerRegistry: '$(DOCKER_REGISTRY)'
  imageName: '${projectName}'
  containerPort: ${port}
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build & Test'
    jobs:
      - job: Lint
        displayName: 'Lint Code'
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '$(nodeVersion)'
          
          - task: Cache@2
            displayName: 'Cache npm packages'
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: $(npm_config_cache)
          
          - script: ${installCmd}
            displayName: 'Install dependencies'
          
          - script: ${lintCmd}
            displayName: 'Run linter'

      - job: Test
        displayName: 'Run Tests'
        dependsOn: Lint
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '$(nodeVersion)'
          
          - script: ${installCmd}
            displayName: 'Install dependencies'
          
          - script: ${testCmd}${includeCoverage ? " --coverage --coverageReporters=cobertura" : ""}
            displayName: 'Run tests'
`;

	if (includeCoverage) {
		content += `          
          - task: PublishCodeCoverageResults@1
            displayName: 'Publish code coverage'
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
              reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
`;
	}

	// Security scanning
	if (
		includeSecurity &&
		(strategy === "comprehensive" || strategy === "security-focused")
	) {
		content += `
      - job: Security
        displayName: 'Security Scanning'
        dependsOn: Lint
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '$(nodeVersion)'
          
          - script: ${installCmd}
            displayName: 'Install dependencies'
          
          - script: npm audit --audit-level=high || true
            displayName: 'npm audit'
`;

		if (strategy === "security-focused") {
			content += `          
          - task: SnykSecurityScan@1
            displayName: 'Snyk Security Scan'
            inputs:
              serviceConnectionEndpoint: 'snyk-connection'
              testType: 'app'
              failOnIssues: false
            continueOnError: true
`;
		}
	}

	// E2E tests
	if (includeE2E) {
		content += `
      - job: E2E
        displayName: 'E2E Tests'
        dependsOn: Test
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '$(nodeVersion)'
          
          - script: ${installCmd}
            displayName: 'Install dependencies'
          
          - script: ${buildCmd}
            displayName: 'Build application'
          
          - script: |
              npm start &
              sleep 10
              npm run test:e2e
            displayName: 'Run E2E tests'
`;
	}

	// Build job
	content += `
      - job: Build
        displayName: 'Build Application'
        dependsOn:
          - Test
`;

	if (
		includeSecurity &&
		(strategy === "comprehensive" || strategy === "security-focused")
	) {
		content += `          - Security
`;
	}

	if (includeE2E) {
		content += `          - E2E
`;
	}

	content += `        pool:
          vmImage: $(vmImageName)
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '$(nodeVersion)'
          
          - script: ${installCmd}
            displayName: 'Install dependencies'
          
          - script: ${buildCmd}
            displayName: 'Build application'
          
          - task: PublishBuildArtifacts@1
            displayName: 'Publish artifacts'
            inputs:
              pathToPublish: 'dist'
              artifactName: 'dist'

  - stage: Docker
    displayName: 'Docker Build & Push'
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/${branch}'))
    jobs:
      - job: DockerBuild
        displayName: 'Build & Push Docker Image'
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: 'Build Docker image'
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: '$(imageName)'
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)
                latest
          
          - task: Docker@2
            displayName: 'Push Docker image'
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: '$(imageName)'
              command: 'push'
              tags: |
                $(Build.BuildId)
                latest
`;

	// Container scan
	if (includeSecurity) {
		content += `          
          - task: trivy@1
            displayName: 'Container vulnerability scan'
            inputs:
              image: '$(dockerRegistry)/$(imageName):$(Build.BuildId)'
              exitCode: 0
            continueOnError: true
`;
	}

	// Deploy stage
	if (deployTarget !== "none") {
		content += generateAzureDeployStage(deployTarget, branch);
	}

	return content;
}

function generateAzureDeployStage(target: string, branch: string): string {
	switch (target) {
		case "kubernetes":
			return `
  - stage: Deploy
    displayName: 'Deploy to Kubernetes'
    dependsOn: Docker
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/${branch}'))
    jobs:
      - deployment: DeployToK8s
        displayName: 'Deploy to AKS'
        pool:
          vmImage: $(vmImageName)
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: KubernetesManifest@0
                  displayName: 'Deploy to Kubernetes'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: '$(kubernetesServiceConnection)'
                    namespace: 'default'
                    manifests: |
                      k8s/deployment.yaml
                      k8s/service.yaml
                    containers: |
                      $(dockerRegistry)/$(imageName):$(Build.BuildId)
`;

		case "ecs":
			return `
  - stage: Deploy
    displayName: 'Deploy to AWS ECS'
    dependsOn: Docker
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/${branch}'))
    jobs:
      - deployment: DeployToECS
        displayName: 'Deploy to ECS'
        pool:
          vmImage: $(vmImageName)
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AWSCLI@1
                  displayName: 'Update ECS Service'
                  inputs:
                    awsCredentials: '$(awsServiceConnection)'
                    regionName: '$(awsRegion)'
                    awsCommand: 'ecs'
                    awsSubCommand: 'update-service'
                    awsArguments: '--cluster $(ecsCluster) --service $(ecsService) --force-new-deployment'
`;

		case "cloudrun":
			return `
  - stage: Deploy
    displayName: 'Deploy to Cloud Run'
    dependsOn: Docker
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/${branch}'))
    jobs:
      - deployment: DeployToCloudRun
        displayName: 'Deploy to Cloud Run'
        pool:
          vmImage: $(vmImageName)
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: GoogleCloudSdkTool@0
                  displayName: 'Install gcloud'
                
                - script: |
                    gcloud run deploy expressots-app \\
                      --image $(dockerRegistry)/$(imageName):$(Build.BuildId) \\
                      --region $(gcpRegion) \\
                      --platform managed
                  displayName: 'Deploy to Cloud Run'
`;

		default:
			return `
  - stage: Deploy
    displayName: 'Deploy'
    dependsOn: Docker
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/${branch}'))
    jobs:
      - deployment: Deploy
        displayName: 'Deploy to ${target}'
        pool:
          vmImage: $(vmImageName)
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Deploying to ${target}"
                  displayName: 'Deploy'
`;
	}
}
