import fs from "fs";
import path from "path";
import chalk from "chalk";
import {
	getAuditCommand,
	getCiInstallCommand,
	getRunScriptCommand,
} from "../../utils/package-manager-commands";
import type { GeneratorOptions } from "./github-actions";
import { loadCICDTemplate, logTemplateSource } from "./template-loader";

export async function generateBitbucketPipelines(
	outputDir: string,
	options: GeneratorOptions,
): Promise<void> {
	// Try remote template, fall back to embedded
	const result = await loadCICDTemplate(
		"bitbucket",
		options.strategy,
		options,
		generateBitbucketContentEmbedded,
	);

	logTemplateSource("Bitbucket", result.source);

	const filePath = path.join(outputDir, "bitbucket-pipelines.yml");
	fs.writeFileSync(filePath, result.content, "utf-8");
	console.log(chalk.green(`  ✓ Created bitbucket-pipelines.yml`));
}

/**
 * Embedded template generator (fallback when remote templates unavailable)
 */
function generateBitbucketContentEmbedded(options: GeneratorOptions): string {
	const {
		nodeVersion,
		packageManager,
		strategy,
		includeSecurity,
		includeE2E,
		includeCoverage,
		deployTarget,
		branch,
	} = options;

	const installCmd = getCiInstallCommand(packageManager, {
		bootstrapBun: true,
	});
	const testCmd = getRunScriptCommand(packageManager, "test");
	const buildCmd = getRunScriptCommand(packageManager, "build");
	const lintCmd = getRunScriptCommand(packageManager, "lint");
	const startCmd = getRunScriptCommand(packageManager, "start");
	const e2eCmd = getRunScriptCommand(packageManager, "test:e2e");
	const auditCmd = getAuditCommand(packageManager);

	let content = `# Bitbucket Pipelines
# Generated by ExpressoTS CLI
# Strategy: ${strategy}

image: node:${nodeVersion}

definitions:
  caches:
    npm: ~/.npm
  
  steps:
    - step: &lint
        name: Lint
        caches:
          - npm
          - node
        script:
          - ${installCmd}
          - ${lintCmd}
    
    - step: &test
        name: Test
        caches:
          - npm
          - node
        script:
          - ${installCmd}
          - ${testCmd}${includeCoverage ? " --coverage" : ""}
`;

	if (includeCoverage) {
		content += `        artifacts:
          - coverage/**
`;
	}

	content += `    
    - step: &build
        name: Build
        caches:
          - npm
          - node
        script:
          - ${installCmd}
          - ${buildCmd}
        artifacts:
          - dist/**
    
    - step: &docker-build
        name: Docker Build & Push
        services:
          - docker
        caches:
          - docker
        script:
          - docker build -t \${DOCKER_IMAGE}:\${BITBUCKET_COMMIT} .
          - docker tag \${DOCKER_IMAGE}:\${BITBUCKET_COMMIT} \${DOCKER_IMAGE}:latest
          - echo \${DOCKER_PASSWORD} | docker login -u \${DOCKER_USERNAME} --password-stdin
          - docker push \${DOCKER_IMAGE}:\${BITBUCKET_COMMIT}
          - docker push \${DOCKER_IMAGE}:latest

`;

	// Security step
	if (
		includeSecurity &&
		(strategy === "comprehensive" || strategy === "security-focused")
	) {
		content += `    - step: &security
        name: Security Scan
        script:
          - ${auditCmd} || true
          - pipe: aquasecurity/trivy-pipe:1.0.0
            variables:
              imageRef: '.'
              severity: 'HIGH,CRITICAL'

`;
	}

	// E2E step
	if (includeE2E) {
		content += `    - step: &e2e
        name: E2E Tests
        caches:
          - npm
          - node
        script:
          - ${installCmd}
          - ${buildCmd}
          - ${startCmd} &
          - sleep 10
          - ${e2eCmd}

`;
	}

	// Deploy step
	if (deployTarget !== "none") {
		content += generateBitbucketDeployStep(deployTarget);
	}

	// Pipelines configuration
	content += `pipelines:
  default:
    - step: *lint
    - step: *test
`;

	if (
		includeSecurity &&
		(strategy === "comprehensive" || strategy === "security-focused")
	) {
		content += `    - step: *security
`;
	}

	content += `    - step: *build

  branches:
    ${branch}:
      - step: *lint
      - step: *test
`;

	if (
		includeSecurity &&
		(strategy === "comprehensive" || strategy === "security-focused")
	) {
		content += `      - step: *security
`;
	}

	if (includeE2E) {
		content += `      - step: *e2e
`;
	}

	content += `      - step: *build
      - step: *docker-build
`;

	if (deployTarget !== "none") {
		content += `      - step: *deploy

`;
	}

	content += `
  pull-requests:
    '**':
      - step: *lint
      - step: *test
`;

	return content;
}

function generateBitbucketDeployStep(target: string): string {
	switch (target) {
		case "kubernetes":
			return `    - step: &deploy
        name: Deploy to Kubernetes
        deployment: production
        script:
          - pipe: atlassian/kubectl-run:3.0.0
            variables:
              KUBE_CONFIG: \${KUBE_CONFIG}
              KUBECTL_COMMAND: 'set image deployment/expressots-app app=\${DOCKER_IMAGE}:\${BITBUCKET_COMMIT}'
          - pipe: atlassian/kubectl-run:3.0.0
            variables:
              KUBE_CONFIG: \${KUBE_CONFIG}
              KUBECTL_COMMAND: 'rollout status deployment/expressots-app'

`;

		case "railway":
			return `    - step: &deploy
        name: Deploy to Railway
        deployment: production
        script:
          - npm install -g @railway/cli
          - railway up

`;

		default:
			return `    - step: &deploy
        name: Deploy
        deployment: production
        script:
          - echo "Deploying to ${target}"

`;
	}
}
