import fs from "fs";
import path from "path";
import chalk from "chalk";
import {
	getCiInstallCommand,
	getLockfileName,
	getRunScriptCommand,
} from "../../utils/package-manager-commands";
import type { GeneratorOptions } from "./github-actions";
import { loadCICDTemplate, logTemplateSource } from "./template-loader";

export async function generateCircleCI(
	outputDir: string,
	options: GeneratorOptions,
): Promise<void> {
	const circleDir = path.join(outputDir, ".circleci");
	fs.mkdirSync(circleDir, { recursive: true });

	// Try remote template, fall back to embedded
	const result = await loadCICDTemplate(
		"circleci",
		options.strategy,
		options,
		generateCircleCIContentEmbedded,
	);

	logTemplateSource("CircleCI", result.source);

	const filePath = path.join(circleDir, "config.yml");
	fs.writeFileSync(filePath, result.content, "utf-8");
	console.log(chalk.green(`  ✓ Created .circleci/config.yml`));
}

/**
 * Embedded template generator (fallback when remote templates unavailable)
 */
function generateCircleCIContentEmbedded(options: GeneratorOptions): string {
	const {
		nodeVersion,
		packageManager,
		strategy,
		includeSecurity,
		includeE2E,
		includeCoverage,
		deployTarget,
		branch,
	} = options;

	const installCmd = getCiInstallCommand(packageManager, {
		bootstrapBun: true,
	});
	const testCmd = getRunScriptCommand(packageManager, "test");
	const buildCmd = getRunScriptCommand(packageManager, "build");
	const lintCmd = getRunScriptCommand(packageManager, "lint");
	const startCmd = getRunScriptCommand(packageManager, "start");
	const e2eCmd = getRunScriptCommand(packageManager, "test:e2e");
	const lockfile = getLockfileName(packageManager);

	let content = `# CircleCI Configuration
# Generated by ExpressoTS CLI
# Strategy: ${strategy}

version: 2.1

orbs:
  node: circleci/node@5.2
  docker: circleci/docker@2.5

executors:
  node-executor:
    docker:
      - image: cimg/node:${nodeVersion}
    working_directory: ~/project

commands:
  install-deps:
    steps:
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "${lockfile}" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: ${installCmd}
      - save_cache:
          key: v1-deps-{{ checksum "${lockfile}" }}
          paths:
            - node_modules

jobs:
  lint:
    executor: node-executor
    steps:
      - checkout
      - install-deps
      - run:
          name: Run linter
          command: ${lintCmd}

  test:
    executor: node-executor
    steps:
      - checkout
      - install-deps
      - run:
          name: Run tests
          command: ${testCmd}${includeCoverage ? ` --coverage` : ""}
`;

	if (includeCoverage) {
		content += `      - store_artifacts:
          path: coverage
      - run:
          name: Upload coverage
          command: |
            if [ -n "$CODECOV_TOKEN" ]; then
              npx codecov
            fi

`;
	} else {
		content += `
`;
	}

	// Security job
	if (
		includeSecurity &&
		(strategy === "comprehensive" || strategy === "security-focused")
	) {
		content += `  security:
    docker:
      - image: aquasec/trivy:latest
    steps:
      - checkout
      - run:
          name: Run security scan
          command: trivy fs --exit-code 0 --severity HIGH,CRITICAL .

`;
	}

	// E2E tests
	if (includeE2E) {
		content += `  e2e:
    executor: node-executor
    steps:
      - checkout
      - install-deps
      - run:
          name: Build application
          command: ${buildCmd}
      - run:
          name: Start application
          command: ${startCmd}
          background: true
      - run:
          name: Wait for app
          command: sleep 10
      - run:
          name: Run E2E tests
          command: ${e2eCmd}

`;
	}

	// Build job
	content += `  build:
    executor: node-executor
    steps:
      - checkout
      - install-deps
      - run:
          name: Build application
          command: ${buildCmd}
      - persist_to_workspace:
          root: .
          paths:
            - dist

  docker-build:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: $CIRCLE_SHA1,latest
      - docker/push:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: $CIRCLE_SHA1,latest

`;

	// Deploy job
	if (deployTarget !== "none") {
		content += generateCircleCIDeployJob(deployTarget);
	}

	// Workflows
	content += `workflows:
  build-and-deploy:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - ${branch}
                - /^feature/.*/
      - test:
          requires:
            - lint
`;

	if (
		includeSecurity &&
		(strategy === "comprehensive" || strategy === "security-focused")
	) {
		content += `      - security:
          requires:
            - lint
`;
	}

	if (includeE2E) {
		content += `      - e2e:
          requires:
            - test
`;
	}

	content += `      - build:
          requires:
            - test
`;

	if (
		includeSecurity &&
		(strategy === "comprehensive" || strategy === "security-focused")
	) {
		content += `            - security
`;
	}

	content += `      - docker-build:
          requires:
            - build
          filters:
            branches:
              only: ${branch}
`;

	if (deployTarget !== "none") {
		content += `      - deploy:
          requires:
            - docker-build
          filters:
            branches:
              only: ${branch}
`;
	}

	return content;
}

function generateCircleCIDeployJob(target: string): string {
	switch (target) {
		case "kubernetes":
			return `  deploy:
    docker:
      - image: bitnami/kubectl:latest
    steps:
      - run:
          name: Deploy to Kubernetes
          command: |
            kubectl set image deployment/expressots-app app=$DOCKER_IMAGE:$CIRCLE_SHA1
            kubectl rollout status deployment/expressots-app

`;

		case "railway":
			return `  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Railway CLI
          command: npm install -g @railway/cli
      - run:
          name: Deploy to Railway
          command: railway up

`;

		default:
			return `  deploy:
    executor: node-executor
    steps:
      - run:
          name: Deploy
          command: echo "Deploy to ${target}"

`;
	}
}
