import fs from "fs";
import path from "path";
import chalk from "chalk";
import type { GeneratorOptions } from "./github-actions";
import { loadCICDTemplate, logTemplateSource } from "./template-loader";

export async function generateGitLabCI(
	outputDir: string,
	options: GeneratorOptions
): Promise<void> {
	// Try remote template, fall back to embedded
	const result = await loadCICDTemplate(
		"gitlab",
		options.strategy,
		options,
		generateGitLabContentEmbedded
	);

	logTemplateSource("GitLab CI", result.source);

	const filePath = path.join(outputDir, ".gitlab-ci.yml");
	fs.writeFileSync(filePath, result.content, "utf-8");
	console.log(chalk.green(`  ✓ Created .gitlab-ci.yml`));
}

/**
 * Embedded template generator (fallback when remote templates unavailable)
 */
function generateGitLabContentEmbedded(options: GeneratorOptions): string {
	const {
		nodeVersion,
		packageManager,
		strategy,
		includeSecurity,
		includeE2E,
		includeCoverage,
		deployTarget,
		branch,
	} = options;

	const installCmd = packageManager === "pnpm" ? "pnpm install" :
		packageManager === "yarn" ? "yarn install" : "npm ci";
	const testCmd = packageManager === "pnpm" ? "pnpm test" :
		packageManager === "yarn" ? "yarn test" : "npm test";
	const buildCmd = packageManager === "pnpm" ? "pnpm build" :
		packageManager === "yarn" ? "yarn build" : "npm run build";
	const lintCmd = packageManager === "pnpm" ? "pnpm lint" :
		packageManager === "yarn" ? "yarn lint" : "npm run lint";

	let content = `# GitLab CI/CD Pipeline
# Generated by ExpressoTS CLI
# Strategy: ${strategy}

image: node:${nodeVersion}-alpine

stages:
  - lint
  - test${includeSecurity && (strategy === "comprehensive" || strategy === "security-focused") ? "\n  - security" : ""}${includeE2E ? "\n  - e2e" : ""}
  - build
  - docker${deployTarget !== "none" ? "\n  - deploy" : ""}

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE

cache:
  key: \${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - node_modules/

# Lint Stage
lint:
  stage: lint
  script:
    - ${installCmd}
    - ${lintCmd}
  only:
    - ${branch}
    - merge_requests

# Test Stage
test:
  stage: test
  script:
    - ${installCmd}
    - ${testCmd}${includeCoverage ? ` --coverage` : ""}
  ${includeCoverage ? `coverage: '/All files[^|]*\\|[^|]*\\s+([\\d\\.]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml` : ""}
  only:
    - ${branch}
    - merge_requests

`;

	// Security scanning
	if (includeSecurity && (strategy === "comprehensive" || strategy === "security-focused")) {
		content += `# Security Stage
security:
  stage: security
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy fs --exit-code 0 --severity HIGH,CRITICAL --format json -o trivy-report.json .
  artifacts:
    reports:
      container_scanning: trivy-report.json
    expire_in: 1 week
  only:
    - ${branch}

`;

		if (strategy === "security-focused") {
			content += `dependency_scanning:
  stage: security
  image: node:${nodeVersion}
  script:
    - npm audit --audit-level=high
  allow_failure: true
  only:
    - ${branch}

`;
		}
	}

	// E2E tests
	if (includeE2E) {
		content += `# E2E Tests
e2e:
  stage: e2e
  services:
    - postgres:15-alpine
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/test"
  script:
    - ${installCmd}
    - ${buildCmd}
    - npm start &
    - sleep 10
    - npm run test:e2e
  only:
    - ${branch}

`;
	}

	// Build stage
	content += `# Build Stage
build:
  stage: build
  script:
    - ${installCmd}
    - ${buildCmd}
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  only:
    - ${branch}

# Docker Build Stage
docker:
  stage: docker
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
    - docker push $DOCKER_IMAGE:latest
  only:
    - ${branch}

`;

	// Deploy stage
	if (deployTarget !== "none") {
		content += generateGitLabDeployJob(deployTarget, branch);
	}

	return content;
}

function generateGitLabDeployJob(target: string, branch: string): string {
	switch (target) {
		case "kubernetes":
			return `# Deploy to Kubernetes
deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl config set-cluster k8s --server="$KUBE_URL"
    - kubectl config set-credentials gitlab --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - kubectl set image deployment/expressots-app app=$DOCKER_IMAGE:$CI_COMMIT_SHA
    - kubectl rollout status deployment/expressots-app
  environment:
    name: production
    url: https://your-app.com
  only:
    - ${branch}
  when: manual

`;

		case "railway":
			return `# Deploy to Railway
deploy:
  stage: deploy
  image: node:20-alpine
  script:
    - npm install -g @railway/cli
    - railway up
  environment:
    name: production
  only:
    - ${branch}
  when: manual

`;

		default:
			return `# Deploy Stage
deploy:
  stage: deploy
  script:
    - echo "Deploy to ${target}"
  environment:
    name: production
  only:
    - ${branch}
  when: manual

`;
	}
}
