import fs from "fs";
import path from "path";
import chalk from "chalk";
import {
	getAuditCommand,
	getCiInstallCommand,
	getRunScriptCommand,
} from "../../utils/package-manager-commands";
import type { GeneratorOptions } from "./github-actions";
import { loadCICDTemplate, logTemplateSource } from "./template-loader";

export async function generateJenkinsfile(
	outputDir: string,
	options: GeneratorOptions,
): Promise<void> {
	// Try remote template, fall back to embedded
	const result = await loadCICDTemplate(
		"jenkins",
		options.strategy,
		options,
		generateJenkinsContentEmbedded,
	);

	logTemplateSource("Jenkins", result.source);

	const filePath = path.join(outputDir, "Jenkinsfile");
	fs.writeFileSync(filePath, result.content, "utf-8");
	console.log(chalk.green(`  ✓ Created Jenkinsfile`));
}

/**
 * Embedded template generator (fallback when remote templates unavailable)
 */
function generateJenkinsContentEmbedded(options: GeneratorOptions): string {
	const {
		projectName,
		nodeVersion,
		packageManager,
		strategy,
		includeSecurity,
		includeE2E,
		includeCoverage,
		deployTarget,
		branch,
	} = options;

	const installCmd = getCiInstallCommand(packageManager, {
		bootstrapBun: true,
	});
	const testCmd = getRunScriptCommand(packageManager, "test");
	const buildCmd = getRunScriptCommand(packageManager, "build");
	const lintCmd = getRunScriptCommand(packageManager, "lint");
	const startCmd = getRunScriptCommand(packageManager, "start");
	const e2eCmd = getRunScriptCommand(packageManager, "test:e2e");
	const auditCmd = getAuditCommand(packageManager);

	let content = `// Jenkinsfile
// Generated by ExpressoTS CLI
// Strategy: ${strategy}

pipeline {
    agent any
    
    environment {
        NODE_VERSION = '${nodeVersion}'
        DOCKER_IMAGE = '${projectName}'
        DOCKER_TAG = "\${BUILD_NUMBER}"
    }
    
    tools {
        nodejs "node-\${NODE_VERSION}"
    }
    
    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Install Dependencies') {
            steps {
                sh '${installCmd}'
            }
        }
        
        stage('Lint') {
            steps {
                sh '${lintCmd}'
            }
        }
        
        stage('Test') {
            steps {
                sh '${testCmd}${includeCoverage ? " --coverage" : ""}'
            }
`;

	if (includeCoverage) {
		content += `            post {
                always {
                    publishHTML(target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'coverage/lcov-report',
                        reportFiles: 'index.html',
                        reportName: 'Coverage Report'
                    ])
                }
            }
`;
	}

	content += `        }
`;

	// Security stage
	if (
		includeSecurity &&
		(strategy === "comprehensive" || strategy === "security-focused")
	) {
		content += `        
        stage('Security Scan') {
            steps {
                script {
                    // Run dependency audit
                    sh '${auditCmd} || true'
                    
                    // Run Trivy if available
                    sh '''
                        if command -v trivy &> /dev/null; then
                            trivy fs --exit-code 0 --severity HIGH,CRITICAL .
                        else
                            echo "Trivy not installed, skipping filesystem scan"
                        fi
                    '''
                }
            }
        }
`;
	}

	// E2E tests
	if (includeE2E) {
		content += `        
        stage('E2E Tests') {
            steps {
                script {
                    sh '${buildCmd}'
                    sh '''
                        ${startCmd} &
                        sleep 10
                        ${e2eCmd}
                    '''
                }
            }
        }
`;
	}

	// Build stage
	content += `        
        stage('Build') {
            steps {
                sh '${buildCmd}'
            }
        }
        
        stage('Docker Build') {
            when {
                branch '${branch}'
            }
            steps {
                script {
                    docker.build("\${DOCKER_IMAGE}:\${DOCKER_TAG}")
                    docker.build("\${DOCKER_IMAGE}:latest")
                }
            }
        }
        
        stage('Docker Push') {
            when {
                branch '${branch}'
            }
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
                        docker.image("\${DOCKER_IMAGE}:\${DOCKER_TAG}").push()
                        docker.image("\${DOCKER_IMAGE}:latest").push()
                    }
                }
            }
        }
`;

	// Deploy stage
	if (deployTarget !== "none") {
		content += generateJenkinsDeployStage(deployTarget, branch);
	}

	content += `    }
    
    post {
        always {
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
`;

	return content;
}

function generateJenkinsDeployStage(target: string, branch: string): string {
	switch (target) {
		case "kubernetes":
			return `        
        stage('Deploy to Kubernetes') {
            when {
                branch '${branch}'
            }
            steps {
                withKubeConfig([credentialsId: 'kubeconfig']) {
                    sh '''
                        kubectl set image deployment/expressots-app \\
                            app=\${DOCKER_IMAGE}:\${DOCKER_TAG}
                        kubectl rollout status deployment/expressots-app
                    '''
                }
            }
        }
`;

		case "railway":
			return `        
        stage('Deploy to Railway') {
            when {
                branch '${branch}'
            }
            steps {
                withCredentials([string(credentialsId: 'railway-token', variable: 'RAILWAY_TOKEN')]) {
                    sh 'npx @railway/cli up'
                }
            }
        }
`;

		default:
			return `        
        stage('Deploy') {
            when {
                branch '${branch}'
            }
            steps {
                echo 'Deploying to ${target}...'
            }
        }
`;
	}
}
