/**
 * Tests for the cicd CI generator (GitHub Actions).
 *
 * Scope: this generator owns the CI half (lint, test, coverage, …).
 * The complementary CD half is generated by `containerize
 * --include-ci` and tested separately. Both must coexist on disk
 * (`ci.yml` vs `cd-docker.yml`) without overwriting each other.
 */

import * as fs from "fs";
import * as os from "os";
import * as path from "path";

jest.mock("../../src/cicd/generators/template-loader", () => {
	const actual = jest.requireActual(
		"../../src/cicd/generators/template-loader",
	);
	return {
		...actual,
		loadCICDTemplate: async (
			_platform: string,
			_strategy: string,
			options: unknown,
			fallback: (opts: unknown) => string,
		) => ({ content: fallback(options), source: "embedded" }),
		logTemplateSource: jest.fn(),
	};
});

import { generateGitHubActions } from "../../src/cicd/generators/github-actions";

let tmpDir: string;
let logSpy: jest.SpyInstance;

beforeEach(() => {
	tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "ex-cli-cicd-"));
	logSpy = jest.spyOn(console, "log").mockImplementation(() => undefined);
});

afterEach(() => {
	logSpy.mockRestore();
	fs.rmSync(tmpDir, { recursive: true, force: true });
});

const baseOptions = {
	projectName: "test-app",
	nodeVersion: "22",
	packageManager: "npm",
	strategy: "comprehensive",
	includeSecurity: true,
	includeE2E: false,
	includeCoverage: true,
	deployTarget: "none",
	branch: "main",
	port: 3000,
};

describe("cicd › generateGitHubActions", () => {
	test("writes .github/workflows/ci.yml (NOT cd-docker.yml)", async () => {
		await generateGitHubActions(tmpDir, { ...baseOptions });

		expect(
			fs.existsSync(path.join(tmpDir, ".github", "workflows", "ci.yml")),
		).toBe(true);
		// Regression guard: this generator must not collide with the
		// containerize CD generator's filename.
		expect(
			fs.existsSync(
				path.join(
					tmpDir,
					".github",
					"workflows",
					"cd-docker.yml",
				),
			),
		).toBe(false);
	});

	test("workflow includes lint, test, and build jobs (the CI essentials)", async () => {
		await generateGitHubActions(tmpDir, { ...baseOptions });
		const yml = fs.readFileSync(
			path.join(tmpDir, ".github", "workflows", "ci.yml"),
			"utf-8",
		);
		expect(yml).toMatch(/^\s*lint:/m);
		expect(yml).toMatch(/^\s*test:/m);
		expect(yml).toMatch(/^\s*build:/m);
	});

	test("install steps respect detected package manager (pnpm)", async () => {
		await generateGitHubActions(tmpDir, {
			...baseOptions,
			packageManager: "pnpm",
		});
		const yml = fs.readFileSync(
			path.join(tmpDir, ".github", "workflows", "ci.yml"),
			"utf-8",
		);
		expect(yml).toContain("pnpm install");
		// Must not silently default to `npm ci` when pm is pnpm.
		expect(yml).not.toMatch(/run:\s+npm ci\b/);
	});

	test("bun project provisions Bun and uses frozen bun install", async () => {
		await generateGitHubActions(tmpDir, {
			...baseOptions,
			packageManager: "bun",
		});
		const yml = fs.readFileSync(
			path.join(tmpDir, ".github", "workflows", "ci.yml"),
			"utf-8",
		);
		expect(yml).toContain("oven-sh/setup-bun");
		expect(yml).toContain("bun install --frozen-lockfile");
		// `cache: 'bun'` is invalid for actions/setup-node and must not
		// be emitted for Bun projects.
		expect(yml).not.toContain("cache: 'bun'");
	});

	test("uses configured trigger branch", async () => {
		await generateGitHubActions(tmpDir, {
			...baseOptions,
			branch: "trunk",
		});
		const yml = fs.readFileSync(
			path.join(tmpDir, ".github", "workflows", "ci.yml"),
			"utf-8",
		);
		expect(yml).toContain("branches: [trunk]");
	});

	test("security-focused strategy adds Trivy scanning", async () => {
		await generateGitHubActions(tmpDir, {
			...baseOptions,
			strategy: "security-focused",
		});
		const yml = fs.readFileSync(
			path.join(tmpDir, ".github", "workflows", "ci.yml"),
			"utf-8",
		);
		expect(yml).toMatch(/aquasecurity\/trivy-action/);
	});

	test("E2E job appears when includeE2E is true", async () => {
		await generateGitHubActions(tmpDir, {
			...baseOptions,
			includeE2E: true,
		});
		const yml = fs.readFileSync(
			path.join(tmpDir, ".github", "workflows", "ci.yml"),
			"utf-8",
		);
		expect(yml).toMatch(/^\s*e2e:/m);
		expect(yml).toMatch(/E2E Tests/);
	});

	test("kubernetes deploy target injects a deploy job", async () => {
		await generateGitHubActions(tmpDir, {
			...baseOptions,
			deployTarget: "kubernetes",
		});
		const yml = fs.readFileSync(
			path.join(tmpDir, ".github", "workflows", "ci.yml"),
			"utf-8",
		);
		expect(yml).toMatch(/Deploy to Kubernetes/);
		expect(yml).toMatch(/kubectl/);
	});

	test("deployTarget=none omits the deploy job", async () => {
		await generateGitHubActions(tmpDir, { ...baseOptions });
		const yml = fs.readFileSync(
			path.join(tmpDir, ".github", "workflows", "ci.yml"),
			"utf-8",
		);
		expect(yml).not.toMatch(/^\s*deploy:/m);
	});
});

describe("cicd › package-manager command helpers", () => {
	test("getCiInstallCommand maps each pm to its strict-lockfile install", async () => {
		const { getCiInstallCommand } = await import(
			"../../src/utils/package-manager-commands"
		);
		expect(getCiInstallCommand("npm")).toBe("npm ci");
		expect(getCiInstallCommand("pnpm")).toBe(
			"pnpm install --frozen-lockfile",
		);
		expect(getCiInstallCommand("yarn")).toBe(
			"yarn install --frozen-lockfile",
		);
		expect(getCiInstallCommand("bun")).toBe(
			"bun install --frozen-lockfile",
		);
		expect(getCiInstallCommand("unknown")).toBe("npm ci");
	});

	test("getRunScriptCommand prepends the right runner per pm", async () => {
		const { getRunScriptCommand } = await import(
			"../../src/utils/package-manager-commands"
		);
		expect(getRunScriptCommand("npm", "test")).toBe("npm run test");
		expect(getRunScriptCommand("pnpm", "test")).toBe("pnpm run test");
		expect(getRunScriptCommand("yarn", "test")).toBe("yarn test");
		expect(getRunScriptCommand("bun", "test")).toBe("bun run test");
	});
});
