/**
 * Stub for iconv-lite on Cloudflare Workers. Generated by the ExpressoTS CLI.
 *
 * express -> body-parser -> iconv-lite pulls in ~485 KiB of character-encoding
 * tables to decode non-UTF-8 request bodies. This target parses bodies in the
 * adapter and disables Express's body middleware, so that code never runs —
 * aliasing the module away (see wrangler.toml and vitest.config.mts) keeps the
 * tables out of the bundle.
 *
 * These throw instead of returning plausible values: reaching them means
 * something is genuinely wrong on this runtime, and a named error is more
 * useful than silently mis-decoded bytes.
 *
 * Delete this file only if you also remove both alias entries.
 */
const UNSUPPORTED =
  "iconv-lite is not available on Cloudflare Workers. Express body-parsing " +
  "middleware does not run on this target — read parsed data from req.body " +
  "instead. To decode bytes yourself, use TextDecoder.";

function unsupported() {
  throw new Error(UNSUPPORTED);
}

module.exports = {
  encodingExists: unsupported,
  decode: unsupported,
  encode: unsupported,
  getDecoder: unsupported,
  getEncoder: unsupported,
};
