import fs from "fs";
import path from "path";
import chalk from "chalk";
import type { MigrationOptions } from "../form";

export async function generateComposeToRender(
	outputDir: string,
	options: MigrationOptions
): Promise<void> {
	console.log(chalk.yellow("  Generating Docker Compose → Render migration..."));

	// Generate render.yaml blueprint
	const renderConfig = generateRenderBlueprint();
	fs.writeFileSync(
		path.join(outputDir, "render.yaml"),
		renderConfig,
		"utf-8"
	);
	console.log(chalk.green("    ✓ Created render.yaml"));

	// Generate checklist
	const checklist = generateRenderFromComposeChecklist();
	fs.writeFileSync(
		path.join(outputDir, "MIGRATION_CHECKLIST.md"),
		checklist,
		"utf-8"
	);
	console.log(chalk.green("    ✓ Created MIGRATION_CHECKLIST.md"));
}

function generateRenderBlueprint(): string {
	return `# Render Blueprint
# Generated by ExpressoTS CLI
# Migrated from Docker Compose

services:
  # Main application service
  - type: web
    name: expressots-app
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      # Reference database if created below
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: expressots-db
      #     property: connectionString
      # - key: REDIS_URL
      #   fromService:
      #     name: expressots-redis
      #     type: redis
      #     property: connectionString

# Uncomment to add PostgreSQL
# databases:
#   - name: expressots-db
#     databaseName: expressots
#     user: expressots
#     plan: starter

# Uncomment to add Redis
# services:
#   - type: redis
#     name: expressots-redis
#     plan: starter
#     maxmemoryPolicy: noeviction
`;
}

function generateRenderFromComposeChecklist(): string {
	return `# Migration Checklist: Docker Compose → Render

## Pre-Migration

- [ ] Review docker-compose.yml
- [ ] Ensure Dockerfile works standalone
- [ ] List all services and their dependencies
- [ ] Document environment variables

## Render Setup

- [ ] Create Render account at https://render.com
- [ ] Connect GitHub/GitLab repository

## Blueprint Deployment

### Option 1: Using render.yaml (Recommended)
- [ ] Copy render.yaml to project root
- [ ] Customize services in render.yaml
- [ ] Push to repository
- [ ] In Render: New → Blueprint → Select repo

### Option 2: Manual Setup
- [ ] Create Web Service in Render dashboard
- [ ] Connect repository
- [ ] Set Docker environment
- [ ] Configure environment variables

## Service Migration

### Main Application
- [ ] Verify Dockerfile builds correctly
- [ ] Set environment variables
- [ ] Configure health check path

### PostgreSQL
- [ ] Create PostgreSQL in Render
- [ ] Update DATABASE_URL env var
- [ ] Migrate data from local/compose database

### Redis
- [ ] Create Redis in Render
- [ ] Update REDIS_URL env var

### Other Services
- [ ] Review any other services in compose
- [ ] Create equivalent Render services or use alternatives

## Environment Variables

Render provides references between services:

\`\`\`yaml
envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: my-db
      property: connectionString
\`\`\`

## Persistent Data

- [ ] Database data: Use Render managed databases
- [ ] File uploads: Use Render Disk or S3
- [ ] Logs: Available in Render dashboard

## Custom Domain

- [ ] Add custom domain in Render settings
- [ ] Update DNS (CNAME to *.onrender.com)
- [ ] SSL is automatic

## Post-Migration

- [ ] Verify all endpoints
- [ ] Check logs in dashboard
- [ ] Monitor performance
- [ ] Remove local docker-compose setup if no longer needed
`;
}
