import fs from "fs";
import path from "path";
import chalk from "chalk";
import type { MigrationOptions } from "../form";
import {
	loadMigrationTemplate,
	buildMigrationVars,
	logTemplateSource,
} from "./template-loader";

export async function generateComposeToK8s(
	outputDir: string,
	options: MigrationOptions,
): Promise<void> {
	console.log(
		chalk.yellow("  Generating Docker Compose → Kubernetes migration..."),
	);
	const vars = buildMigrationVars(options);

	const k8sDir = path.join(outputDir, "k8s");
	fs.mkdirSync(k8sDir, { recursive: true });

	// Generate deployment.yaml
	const deployment = generateDeployment();
	fs.writeFileSync(path.join(k8sDir, "deployment.yaml"), deployment, "utf-8");
	console.log(chalk.green("    ✓ Created k8s/deployment.yaml"));

	// Generate service.yaml
	const service = generateService();
	fs.writeFileSync(path.join(k8sDir, "service.yaml"), service, "utf-8");
	console.log(chalk.green("    ✓ Created k8s/service.yaml"));

	// Generate configmap.yaml
	const configMap = generateConfigMap();
	fs.writeFileSync(path.join(k8sDir, "configmap.yaml"), configMap, "utf-8");
	console.log(chalk.green("    ✓ Created k8s/configmap.yaml"));

	// Generate secrets.yaml template
	const secrets = generateSecrets();
	fs.writeFileSync(path.join(k8sDir, "secrets.yaml"), secrets, "utf-8");
	console.log(chalk.green("    ✓ Created k8s/secrets.yaml"));

	// Generate ingress.yaml
	const ingress = generateIngress();
	fs.writeFileSync(path.join(k8sDir, "ingress.yaml"), ingress, "utf-8");
	console.log(chalk.green("    ✓ Created k8s/ingress.yaml"));

	// Generate kustomization.yaml
	const kustomization = generateKustomization();
	fs.writeFileSync(
		path.join(k8sDir, "kustomization.yaml"),
		kustomization,
		"utf-8",
	);
	console.log(chalk.green("    ✓ Created k8s/kustomization.yaml"));

	// Generate migration checklist
	const checklist = generateK8sChecklist();
	fs.writeFileSync(
		path.join(outputDir, "MIGRATION_CHECKLIST.md"),
		checklist,
		"utf-8",
	);
	console.log(chalk.green("    ✓ Created MIGRATION_CHECKLIST.md"));

	// Generate kompose command reference
	const komposeRef = generateKomposeReference();
	fs.writeFileSync(
		path.join(outputDir, "kompose-reference.md"),
		komposeRef,
		"utf-8",
	);
	console.log(chalk.green("    ✓ Created kompose-reference.md"));
}

function generateDeployment(): string {
	return `# Kubernetes Deployment
# Generated by ExpressoTS CLI
# Migrated from Docker Compose

apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressots-app
  labels:
    app: expressots-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expressots-app
  template:
    metadata:
      labels:
        app: expressots-app
    spec:
      containers:
        - name: app
          image: your-registry/expressots-app:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: expressots-config
            - secretRef:
                name: expressots-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
      imagePullSecrets:
        - name: registry-credentials
`;
}

function generateService(): string {
	return `# Kubernetes Service
# Generated by ExpressoTS CLI

apiVersion: v1
kind: Service
metadata:
  name: expressots-app-service
  labels:
    app: expressots-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: expressots-app
`;
}

function generateConfigMap(): string {
	return `# Kubernetes ConfigMap
# Generated by ExpressoTS CLI
# Non-sensitive configuration values

apiVersion: v1
kind: ConfigMap
metadata:
  name: expressots-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  # Add your non-sensitive config values here
`;
}

function generateSecrets(): string {
	return `# Kubernetes Secrets
# Generated by ExpressoTS CLI
# WARNING: do not commit this file with real values.
# Use: kubectl create secret generic expressots-secrets --from-env-file=.env

apiVersion: v1
kind: Secret
metadata:
  name: expressots-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:pass@host:5432/db"
  API_KEY: "your-api-key"
  # Add your sensitive values here
  # In production, use sealed-secrets or external-secrets
`;
}

function generateIngress(): string {
	return `# Kubernetes Ingress
# Generated by ExpressoTS CLI

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expressots-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - your-domain.com
      secretName: expressots-tls
  rules:
    - host: your-domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: expressots-app-service
                port:
                  number: 80
`;
}

function generateKustomization(): string {
	return `# Kustomization
# Generated by ExpressoTS CLI

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secrets.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: expressots-app
  app.kubernetes.io/managed-by: kustomize
`;
}

function generateK8sChecklist(): string {
	return `# Migration Checklist: Docker Compose → Kubernetes

## Pre-Migration

- [ ] Ensure kubectl is installed and configured
- [ ] Have access to a Kubernetes cluster
- [ ] Push Docker image to container registry

## Automatic Conversion (Optional)

Use Kompose for automatic conversion:
\`\`\`bash
kompose convert -f docker-compose.yml -o k8s/
\`\`\`

## Manual Migration Steps

1. **Deployment**
   - [ ] Update image name in deployment.yaml
   - [ ] Adjust replica count
   - [ ] Configure resource limits

2. **Configuration**
   - [ ] Add non-sensitive values to configmap.yaml
   - [ ] Add sensitive values to secrets.yaml
   - [ ] Never commit secrets with real values!

3. **Networking**
   - [ ] Configure Service (ClusterIP, LoadBalancer, NodePort)
   - [ ] Set up Ingress for external access
   - [ ] Configure TLS/SSL certificates

4. **Storage (if needed)**
   - [ ] Create PersistentVolumeClaims for data
   - [ ] Mount volumes in deployment

## Deployment

\`\`\`bash
# Apply all resources
kubectl apply -k k8s/

# Or apply individually
kubectl apply -f k8s/configmap.yaml
kubectl apply -f k8s/secrets.yaml
kubectl apply -f k8s/deployment.yaml
kubectl apply -f k8s/service.yaml
kubectl apply -f k8s/ingress.yaml
\`\`\`

## Verification

\`\`\`bash
kubectl get pods
kubectl get services
kubectl get ingress
kubectl logs -f deployment/expressots-app
\`\`\`

## Database Migration

If migrating database:
- [ ] Create PersistentVolumeClaim for database
- [ ] Deploy database as StatefulSet
- [ ] Or use managed database service (RDS, Cloud SQL)
`;
}

function generateKomposeReference(): string {
	return `# Kompose Reference

Kompose is a tool to convert Docker Compose files to Kubernetes resources.

## Installation

\`\`\`bash
# macOS
brew install kompose

# Linux
curl -L https://github.com/kubernetes/kompose/releases/download/v1.31.2/kompose-linux-amd64 -o kompose
chmod +x kompose
sudo mv kompose /usr/local/bin/

# Windows
choco install kubernetes-kompose
\`\`\`

## Basic Conversion

\`\`\`bash
# Convert docker-compose.yml
kompose convert

# Output to specific directory
kompose convert -o k8s/

# Generate Helm chart
kompose convert -c
\`\`\`

## Supported Features

| Docker Compose | Kubernetes |
|---------------|------------|
| services | Deployment + Service |
| volumes | PersistentVolumeClaim |
| environment | ConfigMap/Secret |
| ports | Service ports |
| depends_on | (manual ordering) |
| networks | (default pod networking) |

## Limitations

- \`build\` context is not supported (pre-build images)
- \`links\` deprecated, use service DNS
- Some volume types not supported
`;
}
