import fs from "fs";
import path from "path";
import chalk from "chalk";
import type { MigrationOptions } from "../form";
import {
	loadMigrationTemplate,
	buildMigrationVars,
	logTemplateSource,
} from "./template-loader";

export async function generateHerokuToFly(
	outputDir: string,
	options: MigrationOptions,
): Promise<void> {
	console.log(chalk.yellow("  Generating Heroku → Fly.io migration..."));
	const vars = buildMigrationVars(options);

	// Generate fly.toml
	const flyConfig = `# Fly.io Configuration
# Generated by ExpressoTS CLI

app = "expressots-app"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  # Uses Dockerfile by default
  # Or use Nixpacks:
  # builder = "nixpacks"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
`;

	fs.writeFileSync(path.join(outputDir, "fly.toml"), flyConfig, "utf-8");
	console.log(chalk.green("    ✓ Created fly.toml"));

	// Generate migration checklist
	const checklist = generateFlyChecklist();
	fs.writeFileSync(
		path.join(outputDir, "MIGRATION_CHECKLIST.md"),
		checklist,
		"utf-8",
	);
	console.log(chalk.green("    ✓ Created MIGRATION_CHECKLIST.md"));

	// Generate migration scripts (cross-platform)
	const nodeScript = generateFlyMigrationScriptNode();
	fs.writeFileSync(path.join(outputDir, "migrate.js"), nodeScript, "utf-8");
	console.log(chalk.green("    ✓ Created migrate.js (cross-platform)"));

	// Also generate bash script for Unix users
	const bashScript = generateFlyMigrationScriptBash();
	fs.writeFileSync(path.join(outputDir, "migrate.sh"), bashScript, "utf-8");
	console.log(chalk.green("    ✓ Created migrate.sh (Unix/Mac)"));
}

function generateFlyChecklist(): string {
	return `# Migration Checklist: Heroku → Fly.io

## Pre-Migration

Install Fly CLI:
- **Windows**: \`powershell -Command "iwr https://fly.io/install.ps1 -useb | iex"\`
- **Mac/Linux**: \`curl -L https://fly.io/install.sh | sh\`

- [ ] Create account: \`fly auth signup\` or \`fly auth login\`
- [ ] Export Heroku config: \`heroku config --app your-app\`

## Automated Migration Script

\`\`\`bash
# Set your app name
export HEROKU_APP_NAME=your-app   # Mac/Linux
set HEROKU_APP_NAME=your-app      # Windows CMD
$env:HEROKU_APP_NAME="your-app"   # Windows PowerShell

# Run migration
node migrate.js
\`\`\`

## Fly.io Setup

- [ ] Copy \`fly.toml\` to project root
- [ ] Create app: \`fly apps create expressots-app\`
- [ ] Set secrets: \`fly secrets set KEY=value\`

## Database (if using PostgreSQL)

- [ ] Create Fly Postgres: \`fly postgres create\`
- [ ] Attach to app: \`fly postgres attach --app expressots-app\`
- [ ] Export Heroku data and import to Fly Postgres

## Deployment

- [ ] Deploy: \`fly deploy\`
- [ ] Check status: \`fly status\`
- [ ] View logs: \`fly logs\`

## Custom Domain

- [ ] Add certificate: \`fly certs add your-domain.com\`
- [ ] Update DNS to point to Fly

## Scaling

- [ ] Adjust scaling: \`fly scale count 2\`
- [ ] Set memory: \`fly scale memory 512\`

## Post-Migration

- [ ] Verify endpoints
- [ ] Monitor metrics: \`fly dashboard\`
- [ ] Disable Heroku after verification
`;
}

function generateFlyMigrationScriptNode(): string {
	return `#!/usr/bin/env node
/**
 * Migration Script: Heroku → Fly.io
 * Generated by ExpressoTS CLI
 * Cross-platform (Windows, macOS, Linux)
 */

const { execSync } = require('child_process');
const fs = require('fs');

const HEROKU_APP = process.env.HEROKU_APP_NAME || 'your-app';
const FLY_APP = process.env.FLY_APP_NAME || 'expressots-app';

function run(cmd, options = {}) {
    console.log(\`  Running: \${cmd}\`);
    try {
        return execSync(cmd, { encoding: 'utf-8', stdio: 'inherit', ...options });
    } catch (error) {
        if (!options.ignoreError) {
            console.error(\`  Error: \${error.message}\`);
            process.exit(1);
        }
    }
}

function checkCommand(cmd) {
    try {
        execSync(\`\${cmd} version\`, { stdio: 'pipe' });
        return true;
    } catch {
        try {
            execSync(\`\${cmd} --version\`, { stdio: 'pipe' });
            return true;
        } catch {
            return false;
        }
    }
}

async function main() {
    console.log('\\n🪰 Starting Heroku → Fly.io Migration\\n');

    // Check prerequisites
    if (!checkCommand('fly') && !checkCommand('flyctl')) {
        console.error('❌ Fly CLI required.');
        console.error('   Windows: powershell -Command "iwr https://fly.io/install.ps1 -useb | iex"');
        console.error('   Mac/Linux: curl -L https://fly.io/install.sh | sh');
        process.exit(1);
    }

    const flyCmd = checkCommand('flyctl') ? 'flyctl' : 'fly';

    // Export Heroku config (if available)
    if (checkCommand('heroku')) {
        console.log('📦 Exporting Heroku configuration...');
        try {
            const config = execSync(\`heroku config --app \${HEROKU_APP} --shell\`, { encoding: 'utf-8' });
            fs.writeFileSync('.env.heroku', config);
            console.log('  ✓ Exported to .env.heroku');
        } catch {
            console.log('  ⚠ Could not export. Set HEROKU_APP_NAME env var.');
        }
    }

    // Create Fly app
    console.log('\\n🪰 Creating Fly app...');
    run(\`\${flyCmd} apps create \${FLY_APP}\`, { ignoreError: true });

    // Import secrets
    if (fs.existsSync('.env.heroku')) {
        console.log('\\n🔐 Setting secrets...');
        const envContent = fs.readFileSync('.env.heroku', 'utf-8');
        const lines = envContent.split('\\n');
        
        for (const line of lines) {
            const match = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
            if (match) {
                const [, key, value] = match;
                console.log(\`  Setting \${key}...\`);
                run(\`\${flyCmd} secrets set "\${key}=\${value}" --app \${FLY_APP}\`, { ignoreError: true });
            }
        }
    }

    // Deploy
    console.log('\\n🚀 Deploying to Fly.io...');
    run(\`\${flyCmd} deploy\`);

    console.log('\\n✅ Migration complete!');
    console.log(\`   Dashboard: \${flyCmd} dashboard\`);
    console.log(\`   Logs: \${flyCmd} logs\\n\`);
}

main().catch(console.error);
`;
}

function generateFlyMigrationScriptBash(): string {
	return `#!/bin/bash
# Migration Script: Heroku → Fly.io
# Generated by ExpressoTS CLI
# For Unix/macOS - Windows users: use migrate.js instead

set -e

echo "🪰 Starting Heroku → Fly.io Migration"

# Check prerequisites
command -v fly >/dev/null 2>&1 || command -v flyctl >/dev/null 2>&1 || { 
    echo "Fly CLI required. Install: curl -L https://fly.io/install.sh | sh"
    exit 1
}

FLY_CMD="fly"
command -v flyctl >/dev/null 2>&1 && FLY_CMD="flyctl"

# Export Heroku config
echo "📦 Exporting Heroku configuration..."
heroku config --app \${HEROKU_APP_NAME:-your-app} --shell > .env.heroku

# Create Fly app
echo "🪰 Creating Fly app..."
$FLY_CMD apps create \${FLY_APP_NAME:-expressots-app} || echo "App may already exist"

# Set secrets from Heroku config
echo "🔐 Setting secrets..."
while IFS='=' read -r key value; do
    if [[ ! -z "$key" && ! "$key" =~ ^# ]]; then
        echo "  Setting $key..."
        $FLY_CMD secrets set "$key=$value" --app \${FLY_APP_NAME:-expressots-app}
    fi
done < .env.heroku

# Deploy
echo "🚀 Deploying to Fly.io..."
$FLY_CMD deploy

echo "✅ Migration complete!"
echo "   Dashboard: $FLY_CMD dashboard"
echo "   Logs: $FLY_CMD logs"
`;
}
