import fs from "fs";
import path from "path";
import chalk from "chalk";
import type { MigrationOptions } from "../form";
import {
	loadMigrationTemplate,
	buildMigrationVars,
	logTemplateSource,
} from "./template-loader";

export async function generateHerokuToRender(
	outputDir: string,
	options: MigrationOptions,
): Promise<void> {
	console.log(chalk.yellow("  Generating Heroku → Render migration..."));
	const vars = buildMigrationVars(options);

	// Generate render.yaml
	const renderConfig = `# Render Blueprint
# Generated by ExpressoTS CLI

services:
  - type: web
    name: expressots-app
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      # Add your environment variables below
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: expressots-db
      #     property: connectionString

# Uncomment to add a PostgreSQL database
# databases:
#   - name: expressots-db
#     plan: starter
#     databaseName: expressots
#     user: expressots
`;

	fs.writeFileSync(
		path.join(outputDir, "render.yaml"),
		renderConfig,
		"utf-8",
	);
	console.log(chalk.green("    ✓ Created render.yaml"));

	// Generate migration checklist
	const checklist = generateRenderChecklist();
	fs.writeFileSync(
		path.join(outputDir, "MIGRATION_CHECKLIST.md"),
		checklist,
		"utf-8",
	);
	console.log(chalk.green("    ✓ Created MIGRATION_CHECKLIST.md"));

	// Generate environment mapping
	if (options.includeSecrets) {
		const envMapping = generateRenderEnvMapping();
		fs.writeFileSync(
			path.join(outputDir, "env-mapping.md"),
			envMapping,
			"utf-8",
		);
		console.log(chalk.green("    ✓ Created env-mapping.md"));
	}
}

function generateRenderChecklist(): string {
	return `# Migration Checklist: Heroku → Render

## Pre-Migration

- [ ] Export Heroku environment variables
- [ ] Backup database
- [ ] Document Heroku add-ons

## Render Setup

- [ ] Create Render account at https://render.com
- [ ] Copy \`render.yaml\` to project root
- [ ] Connect GitHub/GitLab repository

## Deployment Options

### Option 1: Blueprint (Recommended)
- [ ] Push \`render.yaml\` to repository
- [ ] In Render dashboard, click "New" → "Blueprint"
- [ ] Select your repository
- [ ] Render will create all services defined in render.yaml

### Option 2: Manual Setup
- [ ] Create Web Service in Render dashboard
- [ ] Connect repository
- [ ] Configure build and start commands
- [ ] Set environment variables

## Database Migration

- [ ] Create PostgreSQL in Render
- [ ] Export Heroku database: \`heroku pg:backups:capture\`
- [ ] Download backup: \`heroku pg:backups:download\`
- [ ] Import to Render PostgreSQL

## Environment Variables

- [ ] Set all required environment variables in Render dashboard
- [ ] Configure \`DATABASE_URL\` from Render PostgreSQL

## Custom Domain

- [ ] Add custom domain in Render
- [ ] Update DNS records (CNAME to *.onrender.com)
- [ ] Wait for SSL certificate provisioning

## Post-Migration

- [ ] Verify all endpoints work
- [ ] Monitor logs in Render dashboard
- [ ] Disable Heroku app after verification
`;
}

function generateRenderEnvMapping(): string {
	return `# Environment Variable Mapping: Heroku → Render

## Automatic Variables

| Heroku | Render | Notes |
|--------|--------|-------|
| \`PORT\` | \`PORT\` | Render sets this automatically |
| \`DATABASE_URL\` | \`DATABASE_URL\` | Use fromDatabase in render.yaml |

## Manual Configuration

Set these in Render dashboard or render.yaml:

\`\`\`yaml
envVars:
  - key: NODE_ENV
    value: production
  - key: API_KEY
    sync: false  # Prompt during deploy
  - key: DATABASE_URL
    fromDatabase:
      name: your-db
      property: connectionString
\`\`\`

## Heroku Add-on Equivalents

| Heroku Add-on | Render Alternative |
|---------------|-------------------|
| Heroku Postgres | Render PostgreSQL |
| Heroku Redis | Render Redis |
| Papertrail | Render Logs (built-in) |
| SendGrid | External service |
`;
}
