# Heroku to Render Migration Checklist

Generated by ExpressoTS CLI

## Pre-Migration

- [ ] Export Heroku environment variables
- [ ] Export Heroku add-ons list
- [ ] Backup database if applicable
- [ ] Create Render account at https://render.com

## Migration Steps

### 1. Create Render Service
- [ ] Create new Web Service in Render
- [ ] Connect GitHub/GitLab repository
- [ ] Configure build command
- [ ] Configure start command

### 2. Environment Variables
- [ ] Add all environment variables
- [ ] Configure any secret groups

### 3. Database Migration (if applicable)
- [ ] Create PostgreSQL database in Render
- [ ] Update DATABASE_URL
- [ ] Migrate data

### 4. Testing
- [ ] Deploy to Render
- [ ] Verify application health
- [ ] Test all endpoints

### 5. DNS Cutover
- [ ] Configure custom domain
- [ ] Update DNS records

## Post-Migration

- [ ] Verify all features
- [ ] Update CI/CD pipelines
- [ ] Delete Heroku app
