// Jenkinsfile
// Generated by ExpressoTS CLI
// Strategy: basic
// Template Version: 1.0.0

pipeline {
    agent {
        docker {
            image 'node:{{nodeVersion}}-alpine'
        }
    }

    environment {
        npm_config_cache = "${WORKSPACE}/.npm"
    }

    stages {
        stage('Install') {
            steps {
                sh '{{installCmd}}'
            }
        }

        stage('Lint') {
            steps {
                sh '{{lintCmd}}'
            }
        }

        stage('Test') {
            steps {
                sh '{{testCmd}}'
            }
        }

        stage('Build') {
            steps {
                sh '{{buildCmd}}'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            archiveArtifacts artifacts: 'dist/**/*', fingerprint: true
        }
    }
}
