# Kubernetes ConfigMap
# Generated by ExpressoTS CLI
# Template Version: 1.0.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{appName}}-config
  namespace: {{namespace}}
  labels:
    app: {{appName}}
data:
  NODE_ENV: "production"
  PORT: "{{port}}"
  # Add your application configuration here
  # LOG_LEVEL: "info"
  # API_VERSION: "v1"
