# Kubernetes Deployment
# Generated by ExpressoTS CLI
# Template Version: 1.0.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{appName}}
  namespace: {{namespace}}
  labels:
    app: {{appName}}
spec:
  replicas: {{replicas}}
  selector:
    matchLabels:
      app: {{appName}}
  template:
    metadata:
      labels:
        app: {{appName}}
    spec:
      containers:
      - name: app
        image: your-registry/{{appName}}:latest
        ports:
        - containerPort: {{port}}
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "{{port}}"
        envFrom:
        - configMapRef:
            name: {{appName}}-config
        resources:
          requests:
            memory: "{{memory}}"
            cpu: "{{cpu}}"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: {{healthCheckPath}}
            port: {{port}}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: {{healthCheckPath}}
            port: {{port}}
          initialDelaySeconds: 5
          periodSeconds: 5
