# Kubernetes Ingress
# Generated by ExpressoTS CLI
# Template Version: 1.0.0

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{appName}}-ingress
  namespace: {{namespace}}
  labels:
    app: {{appName}}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - {{appName}}.example.com
      secretName: {{appName}}-tls
  rules:
    - host: {{appName}}.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{appName}}
                port:
                  number: 80
