# Kubernetes Service
# Generated by ExpressoTS CLI
# Template Version: 1.0.0

apiVersion: v1
kind: Service
metadata:
  name: {{appName}}
  namespace: {{namespace}}
  labels:
    app: {{appName}}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{port}}
      protocol: TCP
      name: http
  selector:
    app: {{appName}}
