# Heroku to Railway Migration Checklist

Generated by ExpressoTS CLI

## Pre-Migration

- [ ] Export Heroku environment variables: `heroku config -a <app-name>`
- [ ] Export Heroku add-ons list: `heroku addons -a <app-name>`
- [ ] Backup database if applicable
- [ ] Review current Heroku dyno configuration
- [ ] Create Railway account at https://railway.app

## Migration Steps

### 1. Environment Setup
- [ ] Create new Railway project
- [ ] Link GitHub repository
- [ ] Configure environment variables in Railway dashboard

### 2. Database Migration (if applicable)
- [ ] Provision Railway database
- [ ] Update DATABASE_URL in Railway
- [ ] Migrate data from Heroku database

### 3. Deploy Configuration
- [ ] Review `railway.json` configuration
- [ ] Configure build settings
- [ ] Set start command

### 4. Testing
- [ ] Deploy to Railway staging
- [ ] Verify application starts correctly
- [ ] Test all endpoints
- [ ] Check logs for errors

### 5. DNS & Cutover
- [ ] Configure custom domain in Railway
- [ ] Update DNS records
- [ ] Monitor application health

## Post-Migration

- [ ] Verify all features work correctly
- [ ] Update CI/CD pipelines
- [ ] Update documentation
- [ ] Scale down/delete Heroku app

## Environment Variable Mapping

| Heroku | Railway |
|--------|---------|
| PORT | PORT (auto-configured) |
| DATABASE_URL | DATABASE_URL |
| NODE_ENV | NODE_ENV |
