import * as fs from "fs";
import * as path from "path";
import { Logger } from "../../provider/logger/logger.provider.js";
import type { ViewInfo } from "../render-config.js";

/**
 * Type Generator
 *
 * @description Generates TypeScript type definitions for view files.
 * Provides type safety for view rendering.
 *
 * @public API
 */
export class TypeGenerator {
  private logger: Logger;

  constructor() {
    this.logger = new Logger();
  }

  /**
   * Generate TypeScript types for all views in a directory.
   *
   * @param viewsDir - Directory containing views
   * @param outputFile - Output file path (defaults to views.generated.d.ts)
   */
  async generateViewTypes(
    viewsDir: string,
    outputFile?: string,
  ): Promise<void> {
    try {
      const views = await this.scanViews(viewsDir);

      if (views.length === 0) {
        this.logger.info(
          "No views found, skipping type generation",
          "type-generator",
        );
        return;
      }

      const typeDefinitions = this.generateTypes(views);
      const outputPath =
        outputFile || path.join(viewsDir, "views.generated.d.ts");

      await fs.promises.writeFile(outputPath, typeDefinitions);
      this.logger.info(`Generated view types: ${outputPath}`, "type-generator");
    } catch (error: unknown) {
      this.logger.error(
        `Failed to generate view types: ${(error as Error).message}`,
        "type-generator",
      );
    }
  }

  /**
   * Scan a directory for view files.
   *
   * @param viewsDir - Directory to scan
   * @returns Array of view information
   */
  async scanViews(viewsDir: string): Promise<Array<ViewInfo>> {
    const views: Array<ViewInfo> = [];

    if (!fs.existsSync(viewsDir)) {
      return views;
    }

    await this.scanDirectory(viewsDir, viewsDir, views);
    return views;
  }

  /**
   * Recursively scan a directory.
   *
   * @param dir - Current directory
   * @param baseDir - Base directory for relative paths
   * @param views - Array to populate with view info
   */
  private async scanDirectory(
    dir: string,
    baseDir: string,
    views: Array<ViewInfo>,
  ): Promise<void> {
    const entries = await fs.promises.readdir(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        await this.scanDirectory(fullPath, baseDir, views);
      } else if (entry.isFile() && this.isViewFile(entry.name)) {
        const ext = path.extname(entry.name);
        const relativePath = path.relative(baseDir, fullPath);
        const name = relativePath.replace(ext, "").replace(/\\/g, "/");

        views.push({
          name,
          path: fullPath,
          extension: ext,
          engine: this.mapExtensionToEngine(ext),
          propsType: await this.extractPropsType(fullPath, ext),
        });
      }
    }
  }

  /**
   * Generate TypeScript type definitions.
   *
   * @param views - Array of view information
   * @returns TypeScript type definition string
   */
  private generateTypes(views: Array<ViewInfo>): string {
    const viewTypes = views.map((v) => {
      const propsType = v.propsType || "Record<string, unknown>";
      return `  "${v.name}": ${propsType};`;
    });

    return `/**
 * Auto-generated view types
 * Generated by ExpressoTS Render Engine
 * Do not edit this file manually
 */

/**
 * View name to props type mapping
 */
export interface Views {
${viewTypes.join("\n")}
}

/**
 * All view names
 */
export type ViewName = keyof Views;

/**
 * Get props type for a specific view
 */
export type ViewProps<T extends ViewName> = Views[T];

/**
 * Type-safe render function signature
 */
export type RenderFunction = <T extends ViewName>(
  view: T,
  data: Views[T],
) => Promise<string>;
`;
  }

  /**
   * Check if a file is a view file.
   *
   * @param filename - File name
   * @returns Whether it's a view file
   */
  private isViewFile(filename: string): boolean {
    const viewExtensions = [
      ".ejs",
      ".pug",
      ".jade",
      ".hbs",
      ".handlebars",
      ".tsx",
      ".jsx",
    ];
    const ext = path.extname(filename).toLowerCase();
    return viewExtensions.includes(ext);
  }

  /**
   * Map file extension to engine type.
   *
   * @param extension - File extension
   * @returns Engine type string
   */
  private mapExtensionToEngine(
    extension: string,
  ): "ejs" | "pug" | "hbs" | "react" | "vue" | "svelte" {
    const map: Record<
      string,
      "ejs" | "pug" | "hbs" | "react" | "vue" | "svelte"
    > = {
      ".ejs": "ejs",
      ".pug": "pug",
      ".jade": "pug",
      ".hbs": "hbs",
      ".handlebars": "hbs",
      ".tsx": "react",
      ".jsx": "react",
    };
    return map[extension.toLowerCase()] || "ejs";
  }

  /**
   * Extract props type from a React component.
   *
   * @param filePath - Path to the component file
   * @param extension - File extension
   * @returns Props type string or undefined
   */
  private async extractPropsType(
    filePath: string,
    extension: string,
  ): Promise<string | undefined> {
    // Only extract from React components
    if (extension !== ".tsx" && extension !== ".jsx") {
      return undefined;
    }

    try {
      const content = await fs.promises.readFile(filePath, "utf-8");

      // Simple regex to find interface/type Props
      const propsMatch = content.match(
        /(?:interface|type)\s+(\w*Props)\s*(?:=\s*)?{([^}]+)}/,
      );

      if (propsMatch) {
        // Return inline type
        return `{ ${propsMatch[2].trim()} }`;
      }

      // Check for function component with typed props
      const funcMatch = content.match(
        /(?:function|const)\s+\w+\s*\(\s*(?:{\s*([^}]+)\s*}\s*:\s*(\w+)|props\s*:\s*(\w+))/,
      );

      if (funcMatch) {
        const typeName = funcMatch[2] || funcMatch[3];
        if (typeName && typeName !== "any") {
          return typeName;
        }
      }

      return "Record<string, unknown>";
    } catch {
      return "Record<string, unknown>";
    }
  }
}
