/**
 * DTO Generator Tool
 * Generates Data Transfer Objects with validation
 */

import type { GenerateDtoOptions, GeneratedCode, DtoField } from '../types/index.js';

/** Convert string to PascalCase */
function toPascalCase(str: string): string {
  return str
    .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (_, c) => c.toUpperCase());
}

/** Convert string to kebab-case */
function toKebabCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[_\s]+/g, '-')
    .toLowerCase();
}

/** Map field type to TypeScript type */
function mapType(type: DtoField['type']): string {
  switch (type) {
    case 'string':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'date':
      return 'Date';
    case 'array':
      return 'any[]';
    case 'object':
      return 'Record<string, any>';
    default:
      return 'any';
  }
}

/** Generate validation decorators for a field */
function generateValidationDecorators(field: DtoField): string[] {
  const decorators: string[] = [];
  const v = field.validation;

  // Type validators
  switch (field.type) {
    case 'string':
      decorators.push('@IsString()');
      if (v?.email) decorators.push('@IsEmail()');
      if (v?.url) decorators.push('@IsUrl()');
      if (v?.minLength !== undefined) decorators.push(`@MinLength(${v.minLength})`);
      if (v?.maxLength !== undefined) decorators.push(`@MaxLength(${v.maxLength})`);
      if (v?.pattern) decorators.push(`@Matches(/${v.pattern}/)`);
      break;
    case 'number':
      decorators.push('@IsNumber()');
      if (v?.min !== undefined) decorators.push(`@Min(${v.min})`);
      if (v?.max !== undefined) decorators.push(`@Max(${v.max})`);
      break;
    case 'boolean':
      decorators.push('@IsBoolean()');
      break;
    case 'date':
      decorators.push('@IsDate()');
      break;
    case 'array':
      decorators.push('@IsArray()');
      break;
    case 'object':
      decorators.push('@IsObject()');
      break;
  }

  // Required/Optional
  if (field.required !== false) {
    decorators.push('@IsNotEmpty()');
  } else {
    decorators.push('@IsOptional()');
  }

  return decorators;
}

/** Generate DTO class */
export function generateDto(options: GenerateDtoOptions): GeneratedCode {
  const {
    name,
    fields,
    validation = true,
    outputDir = 'src/dtos',
  } = options;

  const namePascal = toPascalCase(name);
  const nameKebab = toKebabCase(name);

  // Collect all needed imports
  const validatorImports = new Set<string>();
  if (validation) {
    for (const field of fields) {
      const decorators = generateValidationDecorators(field);
      for (const dec of decorators) {
        // Extract decorator name from @DecoratorName(...)
        const match = dec.match(/@(\w+)/);
        if (match) {
          validatorImports.add(match[1]);
        }
      }
    }
  }

  // Build imports section
  let imports = '';
  if (validation && validatorImports.size > 0) {
    imports = `import { ${Array.from(validatorImports).sort().join(', ')} } from 'class-validator';\n\n`;
  }

  // Build class fields
  const fieldLines: string[] = [];
  for (const field of fields) {
    const tsType = mapType(field.type);
    const optional = field.required === false ? '?' : '!';
    
    if (validation) {
      const decorators = generateValidationDecorators(field);
      for (const dec of decorators) {
        fieldLines.push(`  ${dec}`);
      }
    }
    
    fieldLines.push(`  ${field.name}${optional}: ${tsType};`);
    fieldLines.push('');
  }

  const content = `${imports}/**
 * ${namePascal} DTO
 * Auto-generated by ExpressoTS Studio
 */
export class ${namePascal}DTO {
${fieldLines.join('\n').trimEnd()}
}
`;

  return {
    files: [
      {
        path: `${outputDir}/${nameKebab}.dto.ts`,
        content,
        action: 'create',
      },
    ],
    summary: `Generated ${namePascal}DTO with ${fields.length} fields`,
  };
}
