# Docker Compose - Production
# Generated by ExpressoTS CLI
# Template Version: 1.0.0

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: {{projectName}}
    restart: unless-stopped
    ports:
      - "{{port}}:{{port}}"
    environment:
      - NODE_ENV=production
      - PORT={{port}}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:{{port}}{{healthCheckEndpoint}}"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
