# Production Dockerfile
# Generated by ExpressoTS CLI
# Template Version: 1.1.0

# Build stage
FROM {{builderImage}} AS builder

WORKDIR /app

{{nativeDepsSetup}}

{{pmSetup}}

# Copy package files
{{#hasLocalDeps}}
COPY package.docker.json ./package.json
{{/hasLocalDeps}}
{{^hasLocalDeps}}
COPY package*.json ./
{{lockfileCopy}}
{{/hasLocalDeps}}

# Install dependencies
RUN {{installCommand}}

# Copy source code
COPY . .

# Build the application
RUN {{buildCommand}}

# Prune dev dependencies
RUN {{pruneCommand}}

# Production stage
FROM {{runtimeImage}} AS production

WORKDIR /app

# Create non-root user
{{nonRootUserSetup}}

# Copy built files from builder
COPY --from=builder --chown=nodejs:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=nodejs:nodejs /app/dist ./dist
COPY --from=builder --chown=nodejs:nodejs /app/package*.json ./

# Set environment variables
ENV NODE_ENV={{nodeEnv}}
ENV PORT={{port}}

# Switch to non-root user
USER nodejs

# Expose port
EXPOSE {{port}}

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=40s --retries=3 \
    CMD node -e "require('http').get('http://localhost:{{port}}{{healthCheckEndpoint}}', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"

# Start the application
CMD ["node", "{{entryPoint}}"]
