# Development Dockerfile
# Generated by ExpressoTS CLI
# Template Version: 1.0.0

FROM node:{{nodeVersion}}-alpine

WORKDIR /app

# Install development tools
RUN apk add --no-cache git

# Copy package files
{{#hasLocalDeps}}
COPY package.docker.json ./package.json
COPY .docker-deps/ ./.docker-deps/
{{/hasLocalDeps}}
{{^hasLocalDeps}}
COPY package*.json ./
{{/hasLocalDeps}}

# Install all dependencies (including dev)
RUN {{installCommand}}

# Copy source code
COPY . .

# Set environment variables
ENV NODE_ENV=development
ENV PORT={{port}}

# Expose port
EXPOSE {{port}}

# Start with hot reload
CMD ["npm", "run", "dev"]
