# Production Dockerfile
# Generated by ExpressoTS CLI
# Template Version: 1.0.0

# Build stage
FROM node:{{nodeVersion}}-alpine AS builder

WORKDIR /app

# Copy package files
{{#hasLocalDeps}}
COPY package.docker.json ./package.json
{{/hasLocalDeps}}
{{^hasLocalDeps}}
COPY package*.json ./
{{/hasLocalDeps}}

# Install dependencies
RUN {{installCommand}}

# Copy source code
COPY . .

# Build the application
RUN {{buildCommand}}

# Prune dev dependencies
RUN npm prune --production

# Production stage
FROM node:{{nodeVersion}}-alpine AS production

WORKDIR /app

# Create non-root user
RUN addgroup -g 1001 -S nodejs && \
    adduser -S expressots -u 1001 -G nodejs

# Copy built files from builder
COPY --from=builder --chown=expressots:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=expressots:nodejs /app/dist ./dist
COPY --from=builder --chown=expressots:nodejs /app/package.json ./

# Set environment variables
ENV NODE_ENV=production
ENV PORT={{port}}

# Switch to non-root user
USER expressots

# Expose port
EXPOSE {{port}}

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:{{port}}{{healthCheckEndpoint}} || exit 1

# Start the application
CMD ["node", "{{entryPoint}}"]
