# Development Dockerfile
# Generated by ExpressoTS CLI
# Template Version: 1.1.0

FROM {{builderImage}}

WORKDIR /app

{{nativeDepsSetup}}

{{pmSetup}}

# Copy package files
{{#hasLocalDeps}}
COPY package.docker.json ./package.json
COPY .docker-deps/ ./.docker-deps/
{{/hasLocalDeps}}
{{^hasLocalDeps}}
COPY package*.json ./
{{lockfileCopy}}
{{/hasLocalDeps}}

# Install all dependencies (including dev)
RUN {{installCommand}}

# Copy source code
COPY . .

# Set environment variables
ENV NODE_ENV=development
ENV PORT={{port}}

# Expose port and debug port
EXPOSE {{port}}
EXPOSE 9229

# Start with hot reload
CMD {{devCmd}}
