# Docker Compose - Development
# Generated by ExpressoTS CLI
# Template Version: 1.0.0

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: {{projectName}}-dev
    ports:
      - "{{port}}:{{port}}"
    environment:
      - NODE_ENV=development
      - PORT={{port}}
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./expressots.config.ts:/app/expressots.config.ts:ro
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
