# Heroku to Fly.io Migration Checklist

Generated by ExpressoTS CLI

## Pre-Migration

- [ ] Export Heroku environment variables
- [ ] Install Fly CLI: `brew install flyctl` or `curl -L https://fly.io/install.sh | sh`
- [ ] Login to Fly: `flyctl auth login`
- [ ] Backup database if applicable

## Migration Steps

### 1. Initialize Fly App
- [ ] Run `flyctl launch` in project directory
- [ ] Review generated `fly.toml`
- [ ] Configure regions

### 2. Environment Variables
- [ ] Set secrets: `flyctl secrets set KEY=value`
- [ ] Review `[env]` section in fly.toml

### 3. Database Migration (if applicable)
- [ ] Create Fly Postgres: `flyctl postgres create`
- [ ] Attach to app: `flyctl postgres attach`
- [ ] Migrate data

### 4. Deploy
- [ ] Deploy: `flyctl deploy`
- [ ] Check status: `flyctl status`
- [ ] View logs: `flyctl logs`

### 5. DNS & Scaling
- [ ] Configure custom domain
- [ ] Scale as needed: `flyctl scale count 2`

## Post-Migration

- [ ] Verify all features
- [ ] Update CI/CD to use Fly
- [ ] Delete Heroku app
