// Deployment Strategy Templates
// Generated by ExpressoTS CLI

export type DeploymentStrategy = "rolling" | "blue-green" | "canary" | "recreate";

export interface DeploymentConfig {
	strategy: DeploymentStrategy;
	platform: "kubernetes" | "docker-swarm" | "ecs";
}

// ==================== KUBERNETES DEPLOYMENT STRATEGIES ====================

export function generateKubernetesRollingUpdate(): string {
	return `apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressots-app
  labels:
    app: expressots-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # Maximum number of pods that can be created over the desired number
      maxUnavailable: 1  # Maximum number of pods that can be unavailable during the update
  selector:
    matchLabels:
      app: expressots-app
  template:
    metadata:
      labels:
        app: expressots-app
        version: v1
    spec:
      containers:
      - name: expressots-app
        image: expressots-app:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
`;
}

export function generateKubernetesBlueGreenDeployment(): string {
	return `# Blue-Green Deployment Strategy
# This requires two separate deployments and switching services

---
# Blue Deployment (Current Production)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressots-app-blue
  labels:
    app: expressots-app
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: expressots-app
      version: blue
  template:
    metadata:
      labels:
        app: expressots-app
        version: blue
    spec:
      containers:
      - name: expressots-app
        image: expressots-app:v1.0.0
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
# Green Deployment (New Version)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressots-app-green
  labels:
    app: expressots-app
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: expressots-app
      version: green
  template:
    metadata:
      labels:
        app: expressots-app
        version: green
    spec:
      containers:
      - name: expressots-app
        image: expressots-app:v2.0.0
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
# Service (switch between blue/green by changing selector)
apiVersion: v1
kind: Service
metadata:
  name: expressots-app-service
spec:
  selector:
    app: expressots-app
    version: blue  # Change to 'green' to switch traffic
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---
# DEPLOYMENT INSTRUCTIONS:
# 1. Initially, blue deployment is live (service points to blue)
# 2. Deploy green deployment with new version
# 3. Test green deployment (you can access it directly via pod IP)
# 4. Switch traffic by updating service selector from 'blue' to 'green':
#    kubectl patch service expressots-app-service -p '{"spec":{"selector":{"version":"green"}}}'
# 5. Monitor for issues
# 6. If issues occur, rollback by switching back to blue:
#    kubectl patch service expressots-app-service -p '{"spec":{"selector":{"version":"blue"}}}'
# 7. Once green is stable, you can delete blue deployment or keep it for next deployment
`;
}

export function generateKubernetesCanaryDeployment(): string {
	return `# Canary Deployment Strategy
# Gradually shift traffic from stable to canary version

---
# Stable Deployment (90% of traffic)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressots-app-stable
  labels:
    app: expressots-app
    version: stable
spec:
  replicas: 9  # 90% of traffic
  selector:
    matchLabels:
      app: expressots-app
      version: stable
  template:
    metadata:
      labels:
        app: expressots-app
        version: stable
    spec:
      containers:
      - name: expressots-app
        image: expressots-app:v1.0.0
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
# Canary Deployment (10% of traffic)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressots-app-canary
  labels:
    app: expressots-app
    version: canary
spec:
  replicas: 1  # 10% of traffic initially
  selector:
    matchLabels:
      app: expressots-app
      version: canary
  template:
    metadata:
      labels:
        app: expressots-app
        version: canary
    spec:
      containers:
      - name: expressots-app
        image: expressots-app:v2.0.0
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
# Service (routes to both stable and canary based on replica count)
apiVersion: v1
kind: Service
metadata:
  name: expressots-app-service
spec:
  selector:
    app: expressots-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---
# CANARY DEPLOYMENT INSTRUCTIONS:
# 1. Deploy stable version with 9 replicas (90% traffic)
# 2. Deploy canary version with 1 replica (10% traffic)
# 3. Monitor metrics (errors, latency, etc.) for canary
# 4. Gradually increase canary replicas:
#    - 10%: stable=9, canary=1
#    - 25%: stable=3, canary=1
#    - 50%: stable=1, canary=1
#    - 75%: stable=1, canary=3
#    - 100%: stable=0, canary=10 (or scale down stable to 0)
# 5. If issues detected, scale canary to 0 immediately
# 6. Once canary is stable at 100%, it becomes the new stable version

# Example commands:
# kubectl scale deployment expressots-app-canary --replicas=2  # 20% traffic
# kubectl scale deployment expressots-app-canary --replicas=5  # 50% traffic
# kubectl scale deployment expressots-app-stable --replicas=0  # 100% to canary
`;
}

export function generateKubernetesRecreateDeployment(): string {
	return `# Recreate Deployment Strategy
# Shuts down old version completely before starting new version
# Results in downtime but ensures no two versions run simultaneously

apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressots-app
  labels:
    app: expressots-app
spec:
  replicas: 3
  strategy:
    type: Recreate  # Shuts down all old pods before creating new ones
  selector:
    matchLabels:
      app: expressots-app
  template:
    metadata:
      labels:
        app: expressots-app
        version: v1
    spec:
      containers:
      - name: expressots-app
        image: expressots-app:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
# USE CASES FOR RECREATE STRATEGY:
# - Database schema migrations that are not backward compatible
# - Applications that cannot handle multiple versions running simultaneously
# - Resource-constrained environments
# - When zero-downtime is not a requirement
# 
# DRAWBACKS:
# - Causes downtime during deployment
# - Not suitable for high-availability applications
`;
}

// ==================== CI/CD DEPLOYMENT SNIPPETS ====================

export function generateGitHubActionsBlueGreenSnippet(): string {
	return `
      # Blue-Green Deployment
      - name: Deploy Green Environment
        run: |
          kubectl apply -f k8s/deployment-green.yaml
          kubectl rollout status deployment/expressots-app-green
          
      - name: Run Smoke Tests
        run: |
          # Test green deployment
          kubectl port-forward deployment/expressots-app-green 8080:3000 &
          sleep 5
          curl -f http://localhost:8080/health || exit 1
          
      - name: Switch Traffic to Green
        run: |
          kubectl patch service expressots-app-service -p '{"spec":{"selector":{"version":"green"}}}'
          echo "Traffic switched to green deployment"
          
      - name: Cleanup Blue Deployment
        run: |
          # Optional: Keep blue for quick rollback or delete after verification
          # kubectl delete deployment expressots-app-blue
          echo "Blue deployment kept for rollback capability"
`;
}

export function generateGitHubActionsCanarySnippet(): string {
	return `
      # Canary Deployment
      - name: Deploy Canary (10%)
        run: |
          kubectl apply -f k8s/deployment-canary.yaml
          kubectl scale deployment expressots-app-canary --replicas=1
          kubectl rollout status deployment/expressots-app-canary
          
      - name: Monitor Canary
        run: |
          echo "Monitoring canary for 5 minutes..."
          sleep 300
          # Add your monitoring checks here
          # Check error rates, latency, etc.
          
      - name: Increase Canary Traffic (50%)
        run: |
          kubectl scale deployment expressots-app-canary --replicas=5
          kubectl scale deployment expressots-app-stable --replicas=5
          
      - name: Monitor Canary at 50%
        run: |
          echo "Monitoring canary at 50% for 5 minutes..."
          sleep 300
          
      - name: Complete Canary Rollout (100%)
        run: |
          kubectl scale deployment expressots-app-canary --replicas=10
          kubectl scale deployment expressots-app-stable --replicas=0
          echo "Canary deployment complete"
`;
}

export function generateGitHubActionsRollingSnippet(): string {
	return `
      # Rolling Update Deployment
      - name: Deploy with Rolling Update
        run: |
          kubectl set image deployment/expressots-app expressots-app=expressots-app:\${{ github.sha }}
          kubectl rollout status deployment/expressots-app
          
      - name: Verify Deployment
        run: |
          kubectl get pods -l app=expressots-app
          kubectl get deployment expressots-app
          
      - name: Run Health Checks
        run: |
          SERVICE_IP=$(kubectl get service expressots-app-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          curl -f http://$SERVICE_IP/health || exit 1
`;
}

// ==================== DOCKER COMPOSE STRATEGIES ====================

export function generateDockerComposeBlueGreen(): string {
	return `# docker-compose.blue-green.yml
# Blue-Green deployment with Docker Compose

version: '3.8'

services:
  # Blue Environment (Current)
  app-blue:
    image: expressots-app:blue
    container_name: expressots-blue
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - app-network
    deploy:
      replicas: 3
      
  # Green Environment (New)
  app-green:
    image: expressots-app:green
    container_name: expressots-green
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - app-network
    deploy:
      replicas: 3
      
  # Load Balancer (nginx)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-blue.conf:/etc/nginx/nginx.conf:ro  # Switch to nginx-green.conf to change
    networks:
      - app-network
    depends_on:
      - app-blue
      - app-green

networks:
  app-network:
    driver: bridge

---
# nginx-blue.conf
events {
  worker_connections 1024;
}

http {
  upstream backend {
    server app-blue:3000;  # Points to blue
  }
  
  server {
    listen 80;
    location / {
      proxy_pass http://backend;
    }
  }
}

---
# nginx-green.conf
events {
  worker_connections 1024;
}

http {
  upstream backend {
    server app-green:3000;  # Points to green
  }
  
  server {
    listen 80;
    location / {
      proxy_pass http://backend;
    }
  }
}

# USAGE:
# 1. docker-compose -f docker-compose.blue-green.yml up -d
# 2. Test green: curl http://app-green:3000/health
# 3. Switch: Replace nginx-blue.conf with nginx-green.conf volume
# 4. Reload: docker-compose -f docker-compose.blue-green.yml restart nginx
`;
}

export function generateDeploymentStrategyReadme(): string {
	return `# Deployment Strategies

This directory contains configuration files for different deployment strategies.

## Available Strategies

### 1. Rolling Update (Default)
- **Zero downtime**: ✅
- **Resource overhead**: Low
- **Rollback speed**: Medium
- **Complexity**: Low

Gradually replaces old pods with new ones. Best for most applications.

\`\`\`bash
kubectl apply -f k8s/deployment-rolling.yaml
\`\`\`

### 2. Blue-Green Deployment
- **Zero downtime**: ✅
- **Resource overhead**: High (2x resources during deployment)
- **Rollback speed**: Instant
- **Complexity**: Medium

Maintains two identical environments. Switch traffic instantly.

\`\`\`bash
kubectl apply -f k8s/deployment-blue.yaml
kubectl apply -f k8s/deployment-green.yaml
# Test green, then switch:
kubectl patch service expressots-app-service -p '{"spec":{"selector":{"version":"green"}}}'
\`\`\`

### 3. Canary Deployment
- **Zero downtime**: ✅
- **Resource overhead**: Medium
- **Rollback speed**: Fast
- **Complexity**: High

Gradually shifts traffic to new version. Monitor and adjust.

\`\`\`bash
kubectl apply -f k8s/deployment-canary.yaml
# Monitor metrics, then scale:
kubectl scale deployment expressots-app-canary --replicas=5
\`\`\`

### 4. Recreate
- **Zero downtime**: ❌
- **Resource overhead**: None
- **Rollback speed**: Slow
- **Complexity**: Low

Shuts down old version before deploying new. Use when zero-downtime is not required.

\`\`\`bash
kubectl apply -f k8s/deployment-recreate.yaml
\`\`\`

## Choosing a Strategy

| Scenario | Recommended Strategy |
|----------|---------------------|
| Standard web application | Rolling Update |
| Critical production app | Blue-Green |
| Testing new features | Canary |
| Database migration | Recreate |
| Resource-constrained | Rolling Update |
| Need instant rollback | Blue-Green |

## Best Practices

1. **Always test** in staging first
2. **Monitor metrics** during deployment
3. **Have rollback plan** ready
4. **Use health checks** in all strategies
5. **Automate** deployment process
6. **Document** your deployment procedure

## Rollback Procedures

### Rolling Update
\`\`\`bash
kubectl rollout undo deployment/expressots-app
\`\`\`

### Blue-Green
\`\`\`bash
kubectl patch service expressots-app-service -p '{"spec":{"selector":{"version":"blue"}}}'
\`\`\`

### Canary
\`\`\`bash
kubectl scale deployment expressots-app-canary --replicas=0
\`\`\`

## Further Reading

- [Kubernetes Deployment Strategies](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/)
- [Progressive Delivery](https://www.getambassador.io/docs/argo/latest/)
- [Flagger (Automated Canary)](https://flagger.app/)
`;
}
