import fs from "fs";
import path from "path";
import chalk from "chalk";
import type { ProjectAnalysis } from "../analyzers/project-analyzer";
import { loadDockerTemplate, logTemplateSource, type DockerTemplateVars } from "./template-loader";

type GeneratorOptions = {
	environment: string;
	preset: string;
	[key: string]: any;
};

export async function generateDockerCompose(
	options: GeneratorOptions,
	analysis?: ProjectAnalysis,
): Promise<void> {
	const cwd = process.cwd();

	console.log(chalk.yellow(`📝 Generating docker-compose.yml...`));

	// Always generate production docker-compose.yml plus environment-specific if needed
	const environments = options.environment === "all"
		? ["development", "production"]
		: options.environment === "development"
			? ["development", "production"]  // Also generate production compose
			: [options.environment];

	for (const env of environments) {
		const templateType = env === "production" ? "compose" : "compose-development";
		const vars: DockerTemplateVars = {
			nodeVersion: analysis?.nodeVersion || "20",
			packageManager: "npm",
			entryPoint: "dist/src/main.js",
			port: analysis?.port || 3000,
			hasLocalDeps: analysis?.hasLocalDependencies || false,
			healthCheckEndpoint: analysis?.healthCheckPaths?.[0] || "/health",
			projectName: "expressots-app",
			installCommand: "npm ci",
			buildCommand: "npm run build",
		};

		// Try remote template, fall back to embedded
		const result = await loadDockerTemplate(
			templateType,
			vars,
			() => generateDockerComposeContent(env, analysis)
		);

		logTemplateSource(`docker-compose.${env}`, result.source);

		const filename = env === "production"
			? "docker-compose.yml"
			: `docker-compose.${env}.yml`;
		const filepath = path.join(cwd, filename);

		fs.writeFileSync(filepath, result.content, "utf-8");
		console.log(chalk.green(`  ✓ Created ${filename}`));
	}
}

function generateDockerComposeContent(
	environment: string,
	analysis?: ProjectAnalysis,
): string {
	const port = analysis?.port || 3000;
	const hasDatabase = analysis?.hasDatabase || false;
	const hasRedis = analysis?.hasRedis || false;

	const services: string[] = [];

	// App service
	const appService = generateAppService(environment, port, hasDatabase, hasRedis);
	services.push(appService);

	// Database service
	if (hasDatabase) {
		services.push(generateDatabaseService(environment));
	}

	// Redis service
	if (hasRedis) {
		services.push(generateRedisService(environment));
	}

	return `# Docker Compose configuration
# Generated by ExpressoTS CLI
# Environment: ${environment}

version: '3.8'

services:
${services.join("\n\n")}

${hasDatabase || hasRedis ? `
volumes:
${hasDatabase ? "  postgres_data:\n    driver: local\n" : ""}${hasRedis ? "  redis_data:\n    driver: local\n" : ""}
` : ""}
${generateNetworkConfig()}
`;
}

function generateAppService(
	environment: string,
	port: number,
	hasDatabase: boolean,
	hasRedis: boolean,
): string {
	const isDev = environment === "development";
	const dockerfile = isDev ? "Dockerfile.development" : "Dockerfile";

	let service = `  app:
    build:
      context: .
      dockerfile: ${dockerfile}
    container_name: expressots-app-${environment}
    ports:
      - "${port}:${port}"${isDev ? `\n      - "9229:9229"  # Debug port` : ""}`;

	// Environment variables
	service += `\n    environment:
      - NODE_ENV=${environment}
      - PORT=${port}`;

	if (hasDatabase) {
		service += `\n      - DATABASE_URL=postgresql://postgres:password@db:5432/expressots`;
	}

	if (hasRedis) {
		service += `\n      - REDIS_URL=redis://redis:6379`;
	}

	// Volumes (for dev with hot reload)
	if (isDev) {
		service += `\n    volumes:
      - ./src:/app/src
      - /app/node_modules`;
	}

	// Dependencies
	if (hasDatabase || hasRedis) {
		service += `\n    depends_on:`;
		if (hasDatabase) service += `\n      - db`;
		if (hasRedis) service += `\n      - redis`;
	}

	service += `\n    networks:
      - expressots-network`;

	// Restart policy
	if (!isDev) {
		service += `\n    restart: unless-stopped`;
	}

	return service;
}

function generateDatabaseService(environment: string): string {
	return `  db:
    image: postgres:16-alpine
    container_name: expressots-db-${environment}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=expressots
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - expressots-network
    ${environment !== "development" ? "restart: unless-stopped" : ""}`;
}

function generateRedisService(environment: string): string {
	return `  redis:
    image: redis:7-alpine
    container_name: expressots-redis-${environment}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - expressots-network
    ${environment !== "development" ? "restart: unless-stopped" : ""}`;
}

function generateNetworkConfig(): string {
	return `networks:
  expressots-network:
    driver: bridge
`;
}
