import fs from "fs";
import path from "path";
import chalk from "chalk";
import type { ProjectAnalysis } from "../analyzers/project-analyzer";
import { loadKubernetesTemplate, logTemplateSource } from "./template-loader";

type GeneratorOptions = {
	environment: string;
	preset: string;
	[key: string]: any;
};

export async function generateKubernetesConfigs(
	options: GeneratorOptions,
	analysis?: ProjectAnalysis,
): Promise<void> {
	const cwd = process.cwd();
	const k8sDir = path.join(cwd, "k8s");

	if (!fs.existsSync(k8sDir)) {
		fs.mkdirSync(k8sDir, { recursive: true });
	}

	console.log(chalk.yellow(`📝 Generating Kubernetes configurations...`));

	const vars = {
		port: analysis?.port || 3000,
		memory: analysis?.estimatedMemory || "256Mi",
		cpu: analysis?.estimatedCpu || "250m",
		replicas: 3,
		appName: "expressots-app",
		namespace: "default",
		healthCheckPath: analysis?.healthCheckPaths?.[0] || "/health",
	};

	// Generate deployment
	const deploymentResult = await loadKubernetesTemplate(
		"deployment",
		vars,
		() => generateDeployment(options, analysis),
	);
	logTemplateSource("k8s/deployment", deploymentResult.source);
	fs.writeFileSync(
		path.join(k8sDir, "deployment.yaml"),
		deploymentResult.content,
		"utf-8",
	);
	console.log(chalk.green(`  ✓ Created k8s/deployment.yaml`));

	// Generate service
	const serviceResult = await loadKubernetesTemplate("service", vars, () =>
		generateService(options, analysis),
	);
	logTemplateSource("k8s/service", serviceResult.source);
	fs.writeFileSync(
		path.join(k8sDir, "service.yaml"),
		serviceResult.content,
		"utf-8",
	);
	console.log(chalk.green(`  ✓ Created k8s/service.yaml`));

	// Generate config map
	const configMapResult = await loadKubernetesTemplate(
		"configmap",
		vars,
		() => generateConfigMap(options, analysis),
	);
	logTemplateSource("k8s/configmap", configMapResult.source);
	fs.writeFileSync(
		path.join(k8sDir, "configmap.yaml"),
		configMapResult.content,
		"utf-8",
	);
	console.log(chalk.green(`  ✓ Created k8s/configmap.yaml`));
}

function generateDeployment(
	options: GeneratorOptions,
	analysis?: ProjectAnalysis,
): string {
	const port = analysis?.port || 3000;
	const memory = analysis?.estimatedMemory || "256Mi";
	const cpu = analysis?.estimatedCpu || "250m";

	return `# Kubernetes Deployment
# Generated by ExpressoTS CLI

apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressots-app
  labels:
    app: expressots-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: expressots-app
  template:
    metadata:
      labels:
        app: expressots-app
    spec:
      containers:
      - name: app
        image: your-registry/expressots-app:latest
        ports:
        - containerPort: ${port}
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "${port}"
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            memory: "${memory}"
            cpu: "${cpu}"
          limits:
            memory: "${memory === "256Mi" ? "512Mi" : memory}"
            cpu: "${cpu === "250m" ? "500m" : cpu}"
        livenessProbe:
          httpGet:
            path: /health
            port: ${port}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: ${port}
          initialDelaySeconds: 5
          periodSeconds: 5
`;
}

function generateService(
	options: GeneratorOptions,
	analysis?: ProjectAnalysis,
): string {
	const port = analysis?.port || 3000;

	return `# Kubernetes Service
# Generated by ExpressoTS CLI

apiVersion: v1
kind: Service
metadata:
  name: expressots-app
spec:
  type: LoadBalancer
  selector:
    app: expressots-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: ${port}
`;
}

function generateConfigMap(
	options: GeneratorOptions,
	analysis?: ProjectAnalysis,
): string {
	return `# Kubernetes ConfigMap
# Generated by ExpressoTS CLI

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NODE_ENV: "production"
  # Add your configuration here
`;
}
