name: Build and Publish to NPM

on:
  push:
    branches:
      - main
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.11.0"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build:linux

      - name: ExpressoTS Tests
        working-directory: packages/core
        run: npm run test
        env:
          CI: true

      - name: Set up .npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: npm ci
